### PR TITLE
#865 (Vue.js v3) Log errors to console

### LINKED ISSUE #865: Errors are not logged to the console
We've had a few customer support issues related to console logging in development. It seems that by default, Vue logs errors to the console, but errors are not logged to the console when HoneybadgerVue is installed. This is the workaround I've been recommending:

> Our Vue plugin is here:
> 
> https://github.com/honeybadger-io/honeybadger-vue/blob/3fd409efb307e40848a82fe5c5fe702f59517e12/src/index.js
> 
> Something like this might work (this should be configured *before* including Honeybadger):
> 
> ```
> Vue.config.errorHandler = (error, _vm, _info) => {
>   console.log(`Vue error: ${error}`)
> }
> ```

I'd like to research this issue further—what is the default Vue logging behavior? Is there a way we can keep the default logging while also calling HoneybadgerVue's `Vue.config.errorHandler` (and any prior user-configured `Vue.config.errorHandler`, as we currently do?)

Front logo [Front conversations](https://app.frontapp.com/open/top_4xq01)

### PR DESCRIPTION
**Pull request by subzero10**
## Status
**WIP**

## Description
Fixes #865 for Vue.js v3.

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
#880 Log errors to console (vue2) | [link](https://github.com/honeybadger-io/honeybadger-vue/pull/880)

## Todos
- [x] Tests
- [x] Changelog Entry (unreleased)

## Steps to Test or Reproduce
See other PR for steps to reproduce.

### CODE REVIEW

**Comment by subzero10** [comment]
@joshuap Vue.js v3 logs errors in a different way (than v2).
We have a few options to do it:
- Use the same logging functions as in Vue.js v2; this is how [Sentry](https://github.com/getsentry/sentry-javascript/blob/master/packages/vue/src/errorhandler.ts) does it also. Note: we copied the logging function from [Vue.js v2 source code](https://github.com/vuejs/vue/blob/master/src/core/util/debug.js) to do this.
- Like we did for Vue.js v2, we could copy the logging function from [Vue.js v3 source code](https://github.com/vuejs/core/blob/main/packages/runtime-core/src/errorHandling.ts), though it's more than one file and those files have dependencies to other vue.js packages (`@vue/shared` and `@vue/reactivity`).
- Trick Vue.js into thinking that we do not have an errorHandler by unsetting the errorHandler, call their error handling method and finally set the errorHandler again. This is what I did in this PR. I did some initial testing and it works well so far.

Let me know what you think.

**Comment by subzero10** [comment]
> I don't love this approach, mainly unsetting/resetting the custom `errorHandler`

I don't love it either, but to be honest, I'm not sure why:
- What are the consequences of unsetting/resetting the `errorHandler`?
- Is there possibility for memory leaks?
- Are there any performance issues?

> inline Vue's types

Actually, with this solution we are _copying_ the smallest amount of code from vue.js. If you take the solution to vue.js v2 error logging, we had to copy a full [file](https://github.com/honeybadger-io/honeybadger-vue/blob/9a4151c72f1dce1e30d0b4fef646933eda0d2c3b/src/vue-debug.js) to replicate the built-in error logging functionality.
If we were to do the same for vue.js v3, it would be multiple files.
So, it comes down to:
- Copy all files necessary to replicate error logging functionality of vue.js v3.
- Use same logging as in vue.js v2 (as done with Sentry). I assume these logs won't be as informational for vue.js v3.
- Simply do a `console.error()`.

What are your thoughts?

**Comment by subzero10** [comment]
This [PR](https://github.com/honeybadger-io/honeybadger-vue/pull/883) uses same logging mechanism to log errors as in v2.

**Comment by joshuap** [comment]
> > I don't love this approach, mainly unsetting/resetting the custom `errorHandler`
> 
> I don't love it either, but to be honest, I'm not sure why:
> 
> * What are the consequences of unsetting/resetting the `errorHandler`?
> * Is there possibility for memory leaks?
> * Are there any performance issues?
> 
> > inline Vue's types
> 
> Actually, with this solution we are _copying_ the smallest amount of code from vue.js. If you take the solution to vue.js v2 error logging, we had to copy a full [file](https://github.com/honeybadger-io/honeybadger-vue/blob/9a4151c72f1dce1e30d0b4fef646933eda0d2c3b/src/vue-debug.js) to replicate the built-in error logging functionality. If we were to do the same for vue.js v3, it would be multiple files. So, it comes down to:
> 
> * Copy all files necessary to replicate error logging functionality of vue.js v3.
> * Use same logging as in vue.js v2 (as done with Sentry). I assume these logs won't be as informational for vue.js v3.
> * Simply do a `console.error()`.
> 
> What are your thoughts?

Yeah, I don't know exactly why I don't like it either. It's a vague negative feeling. I think it's probably the setting/unsetting globals, mainly. I'm all for copying the least amount of code, though. :)

**Comment by subzero10** [comment]
Closing in favor of #883 .

**Pull request closed without merging**
